/* Manchester Victoria staff-only tools. Static GitHub Pages edition.
   Only live feeds supply train facts. Station information is separately sourced and must be checked.
   No passenger details are collected or stored. */
(()=>{'use strict';
const $=id=>document.getElementById(id);
const MODE=document.body.dataset.tool;
if(!['accessibility','disruption'].includes(MODE))return;
const API='https://api.traini.ac/api', DEPARTURES=API+'/departures/MCV?limit=100';
const FRESH_MS=90000, REFRESH_MS=30000;
const ukClock=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',hour:'2-digit',minute:'2-digit',hour12:false});
const ukDate=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',weekday:'short',day:'numeric',month:'short'});
const state={services:[],lastGood:0,error:'',busy:false,selected:null,station:null,suggest:[],stationController:null,stationTimer:0,stationSeq:0,journeyController:null,journeySeq:0,journeys:[],journeyError:'',journeyAt:0,routeChoice:-1,issueKey:'',reasonMap:new Map(),observedDeparts:new Set(),activityBusy:false};
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const timeMs=x=>{if(!x)return NaN;const y=Date.parse(x);return Number.isFinite(y)?y:NaN};
const time=x=>{const n=typeof x==='number'?x:timeMs(x);return Number.isFinite(n)?ukClock.format(n):'—'};
const stationName=(x,crs='')=>{const c=String(crs||'').toUpperCase(),n=String(x||'').trim();return c==='SFD'||(n.toUpperCase()==='SALFORD'&&c!=='SLD')?'SALFORD CENTRAL':n||c||'Unknown'};
const platform=(x,hidden=false)=>hidden?'':String(x??'').trim().replace(/^platform\s+/i,'').replace(/^(?:TBC|TBD|UNKNOWN|[-—?])$/i,'').toUpperCase();
const displayStatus=s=>s.cancelled?'Cancelled':s.delayed?(s.expected!=='—'&&s.expected!==s.booked?'Expected '+s.expected:'Delayed'):(s.statusText||'Status not supplied');
const reason=s=>s.cancelled?(s.cancelReason||state.reasonMap.get(s.trainId)||''):s.delayed?s.lateReason:'';
const fresh=()=>!!state.lastGood&&!state.error&&Date.now()-state.lastGood<FRESH_MS;
const carriage=s=>{if(!s)return'';if(s.destCrs==='CLH'||s.dest.toUpperCase()==='CLITHEROE')return 'Locally configured: front two carriages for Langho, Whalley and Clitheroe. Verify the formation and current instructions.';if(s.destCrs==='HBL'||s.dest.toUpperCase()==='HEADBOLT LANE')return 'Locally configured: front two carriages for Upholland, Rainford and Headbolt Lane. Verify the formation and current instructions.';return''};
function parseServices(payload){if(!Array.isArray(payload?.results))throw Error('Unexpected departures response');return payload.results.map(raw=>{const status=String(raw.status||'').toLowerCase(),statusText=String(raw.status_text||'').trim(),bookedMs=timeMs(raw.departs),expectedMs=timeMs(raw.expected_departs),delta=expectedMs-bookedMs,cancelled=status==='cancelled'||/^cancelled\b/i.test(statusText),departed=status==='departed'||/^departed\b/i.test(statusText);
 const delayed=!cancelled&&!departed&&(['expected_late','delayed','delayed_no_estimate'].includes(status)||/^delayed\b/i.test(statusText)||(Number.isFinite(delta)&&delta>60000));
 const crs=String(raw.destination?.crs||raw.destination_crs||'').toUpperCase(),dest=stationName(raw.destination?.name||raw.destination_name,crs),points=Array.isArray(raw.calling_points)?raw.calling_points:[],mcv=points.findIndex(p=>String(p.station?.crs||p.crs||'').toUpperCase()==='MCV'||String(p.station?.name||p.name||'').toUpperCase()==='MANCHESTER VICTORIA');
 const stops=(mcv<0?points.filter(p=>String(p.station?.crs||p.crs||'').toUpperCase()!=='MCV'):points.slice(mcv+1)).map(p=>({name:stationName(p.station?.name||p.name,p.station?.crs||p.crs),crs:String(p.station?.crs||p.crs||'').toUpperCase(),scheduled:time(p.scheduled||p.arrives||p.departs),expected:time(p.expected||p.expected_arrives||p.expected_departs)}));
 const trainId=String(raw.train_id||''),headcode=String(raw.headcode||'').toUpperCase();return {key:[trainId||raw.train_uid||headcode||'service',String(raw.departs||'?'),crs||dest].join('|'),trainId,headcode,bookedMs,booked:time(bookedMs),expectedMs,expected:time(expectedMs),dest,destCrs:crs,operator:String(raw.operator||'Operator not supplied'),platform:platform(raw.platform,raw.platform_withheld===true),statusText:statusText||(status==='on_time'?'On time':status||'Status not supplied'),cancelled,departed,delayed,lateReason:String(raw.late_reason||'').trim(),cancelReason:String(raw.cancel_reason||'').trim(),stops,public:raw.not_for_display!==true&&!['freight','empty stock','trip'].includes(String(raw.service_class||'').toLowerCase())}
 }).filter(s=>s.public).sort((a,b)=>(a.bookedMs||Infinity)-(b.bookedMs||Infinity))}
function active(){return state.services.filter(s=>!s.departed&&!state.observedDeparts.has(s.trainId)||(!s.trainId&&!s.departed))}
function clock(){if($('clock'))$('clock').textContent=time(Date.now());if($('date'))$('date').textContent=ukDate.format(Date.now());health();if(MODE==='disruption'&&state.routeChoice>=0&&state.journeyAt&&Date.now()-state.journeyAt>FRESH_MS){$('guidance-text').value='';state.routeChoice=-1;message('guidance-help','Journey result is older than 90 seconds. Search again before preparing a new guidance draft.',true)}}
function health(){const el=$('health');if(!el)return;el.classList.remove('ok','stale','bad');const value=$('health-text'),tip=$('health-age');if(fresh()){el.classList.add('ok');value.textContent='Departures feed connected';tip.textContent='Updated '+time(state.lastGood)+' · Auto-refresh 30s'}else if(state.lastGood){el.classList.add('stale');value.textContent='Departure data may be out of date';tip.textContent='Last successful update '+time(state.lastGood)+(state.error?' · Connection failed':'')}else{el.classList.add('bad');value.textContent=state.error?'Live departure feed unavailable':'Connecting to live departures…';tip.textContent='Do not rely on unconfirmed train data'} }
async function fetchJSON(url,signal){const ctrl=signal?null:new AbortController(),s=signal||ctrl.signal;const timeout=ctrl?setTimeout(()=>ctrl.abort(),10000):null;try{const r=await MCVSite.fetch(url,{signal:s,cache:'no-store'});if(!r.ok)throw Error('Live service returned '+r.status);const d=await r.json();return d}finally{if(timeout)clearTimeout(timeout)}}
async function refreshDepartures(){if(state.busy)return;state.busy=true;try{const before=state.services.find(s=>s.key===state.issueKey);const signature=before?JSON.stringify([before.platform,before.expected,before.cancelled,before.delayed,before.lateReason,before.cancelReason]):null;const priorAssist=state.services.find(s=>s.key===state.selected);const assistSig=priorAssist?JSON.stringify([priorAssist.platform,priorAssist.expected,priorAssist.cancelled,priorAssist.delayed,priorAssist.statusText]):null;const payload=await fetchJSON(DEPARTURES);state.services=parseServices(payload);if(MODE==='accessibility'&&state.selected&&$('handover-text').value){const current=state.services.find(s=>s.key===state.selected);const currentSig=current?JSON.stringify([current.platform,current.expected,current.cancelled,current.delayed,current.statusText]):null;if(currentSig!==assistSig){$('handover-text').value='';message('handover-help','Train information changed. Prepare a fresh handover draft after verifying the new details.',true)}}if(MODE==='disruption'&&state.routeChoice>=0&&state.issueKey){const after=state.services.find(s=>s.key===state.issueKey);const nextSig=after?JSON.stringify([after.platform,after.expected,after.cancelled,after.delayed,after.lateReason,after.cancelReason]):null;if(signature!==nextSig){$('guidance-text').value='';state.routeChoice=-1;message('guidance-help','Affected service information changed. Recheck the route before preparing a new draft.',true)}}state.lastGood=Date.now();state.error='';renderServices();if(MODE==='disruption')renderIssues();else renderAssistanceTrainOptions();}catch(err){state.error=err.message||String(err);renderServices();if(MODE==='disruption')renderIssues();else renderAssistanceTrainOptions();}finally{state.busy=false;health()}}
async function refreshEvents(){if(state.activityBusy)return;state.activityBusy=true;try{const d=await fetchJSON(API+'/stations/MCV/activity?limit=100');if(Array.isArray(d.results)){for(const e of d.results)if(String(e.event_type||'').toUpperCase()==='DEPARTURE'&&e.train_id)state.observedDeparts.add(String(e.train_id));if(state.observedDeparts.size>2000)state.observedDeparts.clear()}}catch{}finally{state.activityBusy=false}}
async function refreshReasons(){try{const r=await fetchJSON(API+'/cancellations?limit=100');if(Array.isArray(r.results)){state.reasonMap=new Map(r.results.filter(x=>x.train_id&&x.reason).map(x=>[String(x.train_id),String(x.reason)]));renderServices();if(MODE==='disruption')renderIssues()}}catch{}}
function tag(s){return `<span class="pill ${s.cancelled?'red':s.delayed?'amber':'green'}">${esc(displayStatus(s))}</span>`}
function serviceCard(s,withButton=false){return `<article class="service ${s.cancelled?'cancelled':s.delayed?'issue':''}"><div class="service-time">${esc(s.booked)}${s.expected!=='—'&&s.expected!==s.booked?`<small>→ ${esc(s.expected)}</small>`:''}</div><div><div class="service-name">${esc(s.dest)}</div><div class="service-meta">${esc(s.operator)}${s.headcode?' · '+esc(s.headcode):''}</div><div class="train-tags">${tag(s)}</div>${s.stops.length?`<details class="stops"><summary>Onward calling points (${s.stops.length})</summary>${esc(s.stops.map(p=>p.name).join(' · '))}</details>`:''}</div><div class="service-platform">${esc(s.platform||'TBC')}</div>${reason(s)?`<div class="service-reason">Reported reason: ${esc(reason(s))}</div>`:''}${withButton?`<button class="btn light service-choose" type="button" data-choose="${esc(s.key)}">Use for assistance note</button>`:''}</article>`}
function renderServices(){const el=$('service-list');if(!el)return;const list=active().filter(s=>!s.cancelled).slice(0,9);el.innerHTML=list.length?list.map(s=>serviceCard(s,true)).join(''):'<p class="load">No operating services currently returned. Check the authorised station systems.</p>';if($('services-count'))$('services-count').textContent=String(list.length);if(MODE==='accessibility'&&state.selected&&!active().some(s=>s.key===state.selected)){state.selected=null;$('assist-selection').textContent='No train selected';$('handover-text').value=''} }
function renderAssistanceTrainOptions(){if(MODE!=='accessibility')return;const list=active().filter(s=>!s.cancelled);const sel=$('assist-service');const v=sel.value;sel.innerHTML='<option value="">Choose a service to prepare a handover</option>'+list.map(s=>`<option value="${esc(s.key)}">${esc(s.booked)} · ${esc(s.dest)} · ${esc(s.platform||'TBC')}${s.headcode?' · '+esc(s.headcode):''}</option>`).join('');if(list.some(s=>s.key===v))sel.value=v;if(state.selected&&!list.some(s=>s.key===state.selected))state.selected=null;if(state.selected&&list.some(s=>s.key===state.selected))sel.value=state.selected;}
function chooseService(key){const s=active().find(x=>x.key===key&&!x.cancelled);if(!s)return;state.selected=key;$('assist-service').value=key;$('assist-selection').textContent=s.booked+' '+s.dest+' · Platform '+(s.platform||'TBC')+' · '+(s.headcode||'No headcode supplied');}
function buildHandover(){if(!fresh())return message('handover-help','Live departures are stale or unavailable. Refresh and check official sources before preparing a train-specific note.',true);const service=active().find(x=>x.key===$('assist-service').value&&!x.cancelled);if(!service)return message('handover-help','Select an operating train first.',true);state.selected=service.key;
 const choices=[...document.querySelectorAll('input[name="needs"]:checked')].map(c=>c.value);const text=`STAFF-ONLY ASSISTANCE HANDOVER — VERIFY BEFORE USE\nManchester Victoria departure · train destination ${service.dest}\nTrain: ${service.booked}${service.expected!=='—'&&service.expected!==service.booked?' (expected '+service.expected+')':''}, platform ${service.platform||'TBC'}, headcode ${service.headcode||'not supplied'}\nNeeds to check: ${choices.length?choices.join('; '):'Confirm required assistance directly with passenger'}\n${carriage(service)?'Locally configured boarding note: '+carriage(service)+'\n':''}Confirm: accessibility and lift status at every station; usable boarding/alighting facilities, boarding point and ramps; connection time and receiving-station arrangements where relevant.\nArrange and record assistance through authorised staff procedures. This tool does not make a booking or notify receiving staff.\nVerified against official systems by: [staff to complete]`;
 $('handover-text').value=text;message('handover-help','Draft prepared. No passenger details are stored or sent by this page.',false)}
function message(id,text,bad){const el=$(id);if(!el)return;el.textContent=text;el.style.color=bad?'#a20734':'#27614a'}
async function copyText(txt,feedback){try{await navigator.clipboard.writeText(txt);message(feedback,'Copied. Verify details before sharing.',false)}catch{const el=document.createElement('textarea');el.value=txt;el.style.position='fixed';el.style.opacity='0';document.body.appendChild(el);el.select();const ok=document.execCommand('copy');el.remove();message(feedback,ok?'Copied. Verify details before sharing.':'Select the text and copy it manually.',!ok)}}
function initStationSearch(){const input=$('station-input');if(!input)return;input.addEventListener('input',()=>{state.station=null;state.suggest=[];clearTimeout(state.stationTimer);state.stationController?.abort();++state.stationSeq;const v=input.value.trim();$('station-hint').textContent=v?'Choose a matching station from suggestions.':'Search for a destination or CRS code.';$('station-list').hidden=true;if(v.length<2)return;state.stationTimer=setTimeout(()=>lookupStations(v),340)});input.addEventListener('focus',()=>{if(input.value.trim().length>=2&&!state.station)lookupStations(input.value.trim())});$('station-list').addEventListener('click',e=>{const btn=e.target.closest('[data-station-code]');if(btn)selectStation(btn.dataset.stationName,btn.dataset.stationCode)});document.addEventListener('click',e=>{if(!e.target.closest('.searchbox'))$('station-list').hidden=true});$('quick-stations')?.addEventListener('click',e=>{const b=e.target.closest('[data-quick-code]');if(b)selectStation(b.dataset.quickName,b.dataset.quickCode)});
 const pre=new URLSearchParams(location.search);const to=pre.get('to');const n=pre.get('name');if(to&&/^[A-Za-z]{3}$/.test(to)&&n&&n.length<=100)selectStation(n,to.toUpperCase());}
async function lookupStations(q){const seq=++state.stationSeq;state.stationController?.abort();const ctrl=new AbortController();state.stationController=ctrl;const el=$('station-list');el.innerHTML='<div class="load">Looking up stations…</div>';el.hidden=false;try{const d=await fetchJSON(API+'/stations?q='+encodeURIComponent(q),ctrl.signal);if(seq!==state.stationSeq||$('station-input').value.trim()!==q)return;state.suggest=(Array.isArray(d.results)?d.results:[]).filter(s=>s.crs&&s.type==='station').slice(0,9).map(s=>({code:String(s.crs).toUpperCase(),name:stationName(s.description||s.name,s.crs)}));el.innerHTML=state.suggest.length?state.suggest.map(s=>`<button type="button" data-station-name="${esc(s.name)}" data-station-code="${esc(s.code)}"><strong>${esc(s.name)}</strong><span>${esc(s.code)}</span></button>`).join(''):'<div class="load">No matching station returned. Try another spelling.</div>';}catch(e){if(e.name==='AbortError'||seq!==state.stationSeq)return;el.innerHTML='<div class="load">Station lookup unavailable. Try again or use the official journey planner.</div>'}}
function selectStation(name,code){state.journeyController?.abort();++state.journeySeq;state.station={name:stationName(name,code),code:String(code).toUpperCase()};$('station-input').value=state.station.name;$('station-list').hidden=true;$('station-hint').textContent=state.station.name+' · '+state.station.code+' selected';if($('destination-access'))$('destination-access').href='https://railmap.nationalrail.co.uk/backend/public/station/'+encodeURIComponent(state.station.code);$('journey-results').innerHTML='<p class="load">Press Find journeys to check live route candidates.</p>';state.journeys=[];state.routeChoice=-1;state.journeyAt=0;if(MODE==='disruption')$('guidance-text').value=''}
async function lookupJourneys(){if(!state.station){$('station-hint').textContent='Select a station from the suggestions first.';$('station-input').focus();return}if(state.station.code==='MCV'){$('station-hint').textContent='Select a destination other than Manchester Victoria.';return}
 if(!fresh()){$('journey-results').innerHTML='<div class="banner amber"><strong>Live departures data unavailable or stale.</strong> Please check official systems before offering a route.</div>';return}
 const seq=++state.journeySeq;state.journeyController?.abort();const ctrl=new AbortController();state.journeyController=ctrl;const btn=$('journey-button');btn.disabled=true;btn.textContent='Finding journeys…';state.journeyAt=0;state.journeyError='';state.journeys=[];state.routeChoice=-1;if(MODE==='disruption')$('guidance-text').value='';$('journey-results').innerHTML='<p class="load">Checking live direct and one-change routes…</p>';
 try{const d=await fetchJSON(API+'/journey/MCV/'+encodeURIComponent(state.station.code)+'?limit=20&max_changes=1&min_interchange_min=12',ctrl.signal);if(seq!==state.journeySeq)return;if(!Array.isArray(d.results))throw Error('Unexpected journey response');state.journeys=d.results.filter(j=>j.not_for_display!==true&&!['freight','empty stock','trip'].includes(String(j.service_class||'').toLowerCase())).sort((a,b)=>timeMs(a.departs)-timeMs(b.departs));state.journeyAt=Date.now();renderJourneys()}catch(e){if(e.name==='AbortError'||seq!==state.journeySeq)return;state.journeyError=e.message||String(e);renderJourneys()}finally{if(seq===state.journeySeq){btn.disabled=false;btn.textContent='Find journeys →'}}}
function serviceForJourney(j){const code=String(j.train_id||j.leg1_train_id||'');const head=String(j.leg1_headcode||j.headcode||'').toUpperCase();const start=timeMs(j.departs);return active().find(s=>(code&&s.trainId===code)||(head&&s.headcode===head&&Number.isFinite(start)&&Math.abs(start-s.bookedMs)<3*60000))||null}
function journeyCard(j,i){const n=Number(j.changes)||0,one=n===1,first=serviceForJourney(j),isCancelled=String(j.status||'').toLowerCase()==='cancelled'||/^cancelled\b/i.test(String(j.status_text||''))||first?.cancelled,disrupted=first?.delayed||/delayed|expected late/i.test(String(j.status_text||'')),atRisk=String(j.connection_status||'').toLowerCase()==='at risk',noConfirm=one&&(!j.connection_status||String(j.connection_status).toLowerCase()==='unknown'),affected=MODE==='disruption'&&first&&first.key===state.issueKey,conn=Number(j.connection_minutes),avail=Number.isFinite(conn)&&conn>0;
 const via=one?stationName(j.interchange?.name,j.interchange?.crs):'',dest=stationName(j.destination?.name||j.destination_name||state.station?.name,j.destination?.crs),booked=time(j.departs),expect=time(j.expected_departs),arrive=time(j.expected_arrives||j.arrives),p=platform(one?j.origin_platform:j.platform,one?j.origin_platform_withheld:j.platform_withheld);
 const issuePill=isCancelled?'<span class="pill red">Cancelled in journey feed</span>':atRisk?'<span class="pill red">Connection at risk</span>':affected?'<span class="pill amber">Same affected service — not an alternative</span>':disrupted?'<span class="pill amber">First train delayed</span>':noConfirm?'<span class="pill amber">Connection unverified</span>':'<span class="pill sky">Route candidate</span>';
 const label=(one?'One change at '+via:'Direct to '+dest);const firstCode=String(j.leg1_headcode||j.headcode||'');let html=`<article class="route-card ${atRisk||isCancelled?'at-risk':affected||noConfirm||disrupted?'maybe':''}"><div class="route-top"><div><div class="route-time">${esc(booked)}${expect!=='—'&&expect!==booked?' → '+esc(expect):''}</div><div class="route-caption">${esc(label)} · Arrive ${esc(arrive)}</div></div><span class="pill sky">Platform ${esc(p||'TBC')}</span></div><div class="pills" style="margin-top:11px"><span class="pill">${one?'1 change':'Direct'}</span>${issuePill}</div>`;
 if(one)html+=`<div class="route-leg"><strong>First train</strong>: ${esc(firstCode||'Headcode not supplied')} ${esc(j.leg1_operator||'')} → ${esc(via)}<br>Interchange: arrive ${esc(time(j.interchange_arrives))} · depart ${esc(time(j.interchange_departs))}${j.leg2_headcode?' · Next headcode '+esc(j.leg2_headcode):''}${avail?' · '+esc(conn)+' min':' · Time not provided'}${j.interchange_departure_platform&&!j.interchange_departure_platform_withheld?' · Interchange platform '+esc(platform(j.interchange_departure_platform)):''}</div>`;
 if(atRisk||noConfirm||one)html+=`<p class="note-footer">${atRisk?'The feed reports this connection at risk. ':noConfirm?'The feed has not verified this connection. ':''}Confirm interchange, actual arrival, accessibility and platform arrangements before advising travel.</p>`;
 else html+=`<div class="route-meta">${esc(j.operator||j.leg1_operator||'Operator not supplied')}${firstCode?' · '+esc(firstCode):''}</div>`;
 if(MODE==='disruption'){html+=`<div class="buttonrow"><button class="btn light" type="button" data-draft-route="${i}" ${isCancelled||affected?'disabled title="Not a valid alternative"':''}>Prepare guidance draft</button></div>`}
 if(MODE==='accessibility')html+=`<p class="note-footer">Train, ramp, destination station and any interchange accessibility have NOT been verified by this route feed.</p>`;
 return html+'</article>'}
function directFallback(){if(!state.station)return[];return active().filter(s=>!s.cancelled&&s.key!==state.issueKey&&(s.destCrs===state.station.code||s.stops.some(p=>p.crs===state.station.code)))}
function renderJourneys(){const el=$('journey-results');if(!el)return;if(!state.station){el.innerHTML='<p class="load">Select a destination to check journeys.</p>';return}
 let html=`<div class="sectionlabel">Manchester Victoria → ${esc(state.station.name)} ${state.journeyAt?'· Checked '+esc(time(state.journeyAt)):''}</div>`;
 if(state.journeyError){const fall=directFallback();html+=`<div class="banner amber"><strong>Journey planner unavailable.</strong> ${esc(state.journeyError)}. The following ${fall.length?'direct departures are from the latest station feed only':'route information cannot be confirmed'}.</div>`;html+=fall.length?fall.slice(0,10).map(s=>serviceCard(s,false)).join(''):'<p class="load">No fallback direct service returned. Use official journey planning tools.</p>'}
 else if(!state.journeys.length)html+='<p class="load">No journey candidates returned. This does not mean there is no usable route. Check the official planner.</p>';
 else{html+='<div class="banner amber"><strong>Route candidates, not confirmed alternatives.</strong> Verify train operation, connections, tickets and accessibility before advising passengers.</div>';html+=state.journeys.slice(0,14).map((j,i)=>journeyCard(j,i)).join('')}
 el.innerHTML=html;}
function renderIssues(){const el=$('issues-list');if(!el)return;const issues=active().filter(s=>s.cancelled||s.delayed).slice(0,40);$('issues-count').textContent=issues.length;el.innerHTML=issues.length?issues.map(s=>`<button class="issue-button ${s.cancelled?'cancelled':''}" type="button" data-issue="${esc(s.key)}" aria-pressed="${s.key===state.issueKey?'true':'false'}"><span><span class="issue-name">${esc(s.dest)}</span><small>${esc(s.operator)}${s.headcode?' · '+esc(s.headcode):''}</small><small>${esc(displayStatus(s))}${reason(s)?' · '+esc(reason(s)):''}</small></span><span class="time-right">${esc(s.booked)}<small>${esc(s.platform||'TBC')}</small></span></button>`).join(''):'<div class="load">No delayed or cancelled services returned in the current departures feed. This is not a network-wide all-clear.</div>';
 if(state.issueKey){const s=issues.find(s=>s.key===state.issueKey);if(!s){state.issueKey='';$('selected-issue').innerHTML='<span class="muted">No affected service selected.</span>';$('guidance-text').value='';state.routeChoice=-1}else $('selected-issue').innerHTML=`<strong>${esc(s.booked)} · ${esc(s.dest)}</strong><br>${esc(displayStatus(s))} · Platform ${esc(s.platform||'TBC')}${s.headcode?' · '+esc(s.headcode):''}${reason(s)?'<br>Feed reason: '+esc(reason(s)):''}<div class="note-footer">Reported train status; verify operational details independently.</div>`}}
function chooseIssue(key){const s=active().find(x=>x.key===key);if(!s)return;state.issueKey=s.key;$('selected-issue').innerHTML=`<strong>${esc(s.booked)} · ${esc(s.dest)}</strong><br>${esc(displayStatus(s))} · Platform ${esc(s.platform||'TBC')}${s.headcode?' · '+esc(s.headcode):''}${reason(s)?'<br>Feed reason: '+esc(reason(s)):''}<div class="note-footer">This is a reported train status, not an independently verified incident cause.</div>`;
 renderIssues();if(s.destCrs&&/^[A-Z]{3}$/.test(s.destCrs)){selectStation(s.dest,s.destCrs)}else{$('station-hint').textContent='Select a destination from the station lookup.'}$('guidance-text').value='';}
function draftRoute(index){if(!fresh()||!state.journeyAt||Date.now()-state.journeyAt>90000){return message('guidance-help','The live train or journey data is stale. Refresh before drafting guidance.',true)}const j=state.journeys[index];if(!j)return;const matched=serviceForJourney(j),one=Number(j.changes)===1;const cancelled=String(j.status||'').toLowerCase()==='cancelled'||matched?.cancelled;if(cancelled||matched?.key===state.issueKey)return message('guidance-help','This candidate is cancelled or is the same affected train. Choose another.',true);
 const from=active().find(s=>s.key===state.issueKey);const platformAtMCV=platform(one?j.origin_platform:j.platform,one?j.origin_platform_withheld:j.platform_withheld)||'not confirmed';const option=one?`change at ${stationName(j.interchange?.name,j.interchange?.crs)}, then onward at ${time(j.interchange_departs)}`:'direct';const instructions=`STAFF-ONLY ALTERNATIVE JOURNEY DRAFT — CHECK BEFORE USE\nFrom: Manchester Victoria\nDestination: ${state.station.name}\n${from?`Affected service: ${from.booked} ${from.dest} (${displayStatus(from)}).\n`:''}Candidate: ${time(j.departs)} from Platform ${platformAtMCV}, ${option}.\nExpected arrival: ${time(j.expected_arrives||j.arrives)}\n${one?`Interchange time: ${Number.isFinite(Number(j.connection_minutes))?j.connection_minutes+' minutes':'not supplied'}; feed connection status: ${j.connection_status||'unverified'}.\n`:''}Check before advising: the chosen train is operating and is not the disrupted service; any platform changes; connection viability; ticket acceptance and route restrictions; step-free access, lift status and assistance arrangements if needed.\nThis page does not book assistance, authorise ticket acceptance or guarantee the route.\nVerified by: [staff to complete]`;
 $('guidance-text').value=instructions;state.routeChoice=index;message('guidance-help','Draft ready. Check it against current official systems before sharing.',false)}
function setup(){const btn=$('refresh-feed');btn?.addEventListener('click',()=>refreshDepartures());$('clock').textContent=time(Date.now());$('date').textContent=ukDate.format(Date.now());setInterval(clock,1000);setInterval(refreshDepartures,REFRESH_MS);setInterval(refreshReasons,120000);setInterval(refreshEvents,15000);initStationSearch();$('journey-form').addEventListener('submit',e=>{e.preventDefault();lookupJourneys()});refreshDepartures();refreshReasons();refreshEvents();
 if(MODE==='accessibility'){
 $('service-list').addEventListener('click',e=>{const b=e.target.closest('[data-choose]');if(b)chooseService(b.dataset.choose)});
 $('assist-service').addEventListener('change',e=>chooseService(e.target.value));$('handover-form').addEventListener('submit',e=>{e.preventDefault();buildHandover()});$('copy-handover').addEventListener('click',()=>{if($('handover-text').value)copyText($('handover-text').value,'handover-help')});
 }else{
 $('issues-list').addEventListener('click',e=>{const b=e.target.closest('[data-issue]');if(b)chooseIssue(b.dataset.issue)});
 $('journey-results').addEventListener('click',e=>{const b=e.target.closest('[data-draft-route]');if(b)draftRoute(Number(b.dataset.draftRoute))});$('copy-guidance').addEventListener('click',()=>{if($('guidance-text').value)copyText($('guidance-text').value,'guidance-help')});
 }
 document.querySelectorAll('a[data-to-sister]').forEach(a=>a.addEventListener('click',()=>{if(state.station){const url=new URL(a.getAttribute('href'),location.href);url.searchParams.set('to',state.station.code);url.searchParams.set('name',state.station.name);a.href=url.pathname+url.search}}));
 }
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();
})();

